name: budget-tools-dev-environment
services:
    transactions-retrieval:
        container_name: transactions-retrieval
        env_file: './apps/transactions-retrieval/.env.${ENV_NAME}'
        build:
            context: .
            dockerfile: ./apps/transactions-retrieval/Dockerfile
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        hostname: postgres
        shm_size: 512MB
        image: postgres:16
        ports:
            - 5432:5432
        volumes:
            - 'postgres-data:/var/lib/postgresql/data'
            - ./init/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
        environment:
            DATABASE_HOST: 127.0.0.1
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            PGDATA: /data/postgres
        healthcheck:
            test:
                - CMD-SHELL
                - 'pg_isready -U ${DB_USER} -d ${DB_NAME}'
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    postgres-data:
