name: budget-tools-dev-environment
services:
    transactions-retrieval:
        container_name: transactions-retrieval
        env_file: './apps/transactions-retrieval/.env.dev'
        environment:
            DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
        build:
            context: .
            dockerfile: ./apps/transactions-retrieval/Dockerfile
        volumes:
            - .:/app
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        hostname: postgres
        shm_size: 512MB
        image: postgres:16
        ports:
            - 5432:5432
        volumes:
            - 'postgres-data:/var/lib/postgresql/data'
            - ./init/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
        environment:
            DATABASE_HOST: 127.0.0.1
            POSTGRES_USER: budget_tools_user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: budget_tools
            PGDATA: /data/postgres
        healthcheck:
            test:
                - CMD-SHELL
                - 'pg_isready -U budget_tools_user -d budget_tools'
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    postgres-data:
