import type { CSSVariablesResolver } from '@mantine/core';

export const cssVariablesResolver: CSSVariablesResolver = () => ({
    variables: {
        '--app-font-display': 'Atkinson Hyperlegible, system-ui, sans-serif',
        '--app-font-body': 'Atkinson Hyperlegible, system-ui, sans-serif',
        '--app-font-mono': 'IBM Plex Mono, ui-monospace, SFMono-Regular, monospace',
    },
    dark: {
        '--app-bg-root': '#161712',
        '--app-bg-surface': '#1f201a',
        '--app-bg-elevated': '#2a2b24',
        '--app-bg-hover': '#2f3028',
        '--app-text-primary': '#f5f3ec',
        '--app-text-secondary': '#c9c6bb',
        '--app-text-muted': '#b0ada3',
        '--app-border': 'rgba(245, 243, 236, 0.12)',
        '--app-border-strong': 'rgba(245, 243, 236, 0.2)',
        '--app-lamp': 'rgba(214, 196, 140, 0.14)',
        '--app-vignette': 'rgba(6, 6, 4, 0.22)',
        '--app-tier-auto': '#9dba92',
        '--app-tier-suggested': '#d4b67a',
        '--app-tier-review': '#e0b45a',
        '--app-tier-blocked': '#b4b0a4',
        '--app-amount-inflow': '#a4d19e',
        '--app-status-error': '#e07a68',
        '--mantine-color-body': '#161712',
        '--mantine-color-text': '#f5f3ec',
    },
    light: {
        '--app-bg-root': '#f3efe6',
        '--app-bg-surface': '#faf7f0',
        '--app-bg-elevated': '#ffffff',
        '--app-bg-hover': '#f0ebe1',
        '--app-text-primary': '#1c1b16',
        '--app-text-secondary': '#6a675e',
        '--app-text-muted': '#8a867c',
        '--app-border': 'rgba(28, 27, 22, 0.08)',
        '--app-border-strong': 'rgba(28, 27, 22, 0.14)',
        '--app-lamp': 'rgba(196, 176, 120, 0.16)',
        '--app-vignette': 'rgba(80, 70, 50, 0.08)',
        '--app-tier-auto': '#4e6848',
        '--app-tier-suggested': '#8a6b32',
        '--app-tier-review': '#9a7420',
        '--app-tier-blocked': '#6a675e',
        '--app-amount-inflow': '#3f6e3c',
        '--app-status-error': '#b42318',
        '--mantine-color-body': '#f3efe6',
        '--mantine-color-text': '#1c1b16',
    },
});
